@startuml _主人公状態遷移
state ActionState {
    state JUMP #CCFFF0
    state DUSH #DDCCFF
    state DUDGE #FFAACC
    state FALL #CCFFCC
    state CLACH #CCFF22
    state Attack #FFCCCC {
        state ATTACK_UP #FFCCCC
        state ATTACK_DOWN #FFCCCC
        state ATTACK_COMBO1 #FFCCCC
        state ATTACK_CHAGE #FFCCCC
    }

    state DAMAGE #FFDDBB
    state DEAD #EEEEEE
}

JUMP -up-> Attack
JUMP -left-> FALL
JUMP -right-> DUSH
JUMP --> DAMAGE
JUMP --> DEAD
JUMP --> DUDGE
JUMP --> CLACH

@enduml