@startuml 壁けり_主人公状態遷移
state ActionState {
    state WALL_KICK #CCFFF0
    state DUSH #DDCCFF
    state DUDGE #FFAACC
    state FALL #CCFFCC
    state CLACH #CCFF22
    state Attack #FFCCCC {
        state ATTACK_UP #FFCCCC
        state ATTACK_DOWN #FFCCCC
        state ATTACK_COMBO1 #FFCCCC
        state ATTACK_CHAGE #FFCCCC
    }

    state DAMAGE #FFDDBB
    state DEAD #EEEEEE
}

WALL_KICK -up-> Attack
WALL_KICK -left-> FALL
WALL_KICK -right-> DUSH
WALL_KICK --> DAMAGE
WALL_KICK --> DEAD
WALL_KICK --> DUDGE
WALL_KICK --> CLACH

@enduml